### ISSUE TITLE
undefined symbol: lame_encode_buffer_interleaved_int

### ISSUE THREAD

**Issue by foobar1994** [aclap-dev/vdhcoapp#127]
vdhcoapp was working fine until recently, but now the video download fails on multiple sites with the following error:
```
/path/to/net.downloadhelper.coapp-1.6.3/converter/build/linux/64/ffmpeg: symbol lookup error: /usr/lib64/libsndfile.so.1: undefined symbol: lame_encode_buffer_interleaved_int
```
Unfortunately I don't really now what changed or was updated that caused the companion app to break.
I use Gentoo Linux, I have packages "libsndfile" and "lame" installed, the latter with the "USE flags" (= compile options) "frontend", "sndfile" and "static-libs". 

If I check with `nm` for the label in the error, it's there:
```
nm -D /usr/lib64/libsndfile.so.1 | grep lame_encode_buffer_interleaved_int
                 U lame_encode_buffer_interleaved_int 
```
I have also tried symlinking my system's ffmpeg in place of the packaged ffmpeg, but that does not change anything.
lame version is 3.100, libsndfile 1.1.0-r1, and VdhCoApp is 1.6.3 with Firefox extension Video DownloadHelper 7.6.0.

Any ideas what could be the problem?

**Comment by denizzzka** [comment]
Probably, it is need to update `libmp3lame0` package

Well known problem for Nov 2022

**Comment by foobar1994** [comment]
Lame is already updated to the latest version, v3.100.

**Comment by Agne21** [comment]
I had the same issue after I added a custom foo.conf in /etc/ld.so.conf.d/ and did "sudo ldconfig"
Suddenly several apps stopped working (okular, pulseaudio plugin, etc ...).
After I remove that file, did "sudo ldconfig" and rebooted, everything was back to normal.
Possibly ldconfig aborted prematurely because of a corrupted library in my added search path.
I think I should stop testing ad hoc apps until I have lots of spare time.

**Comment by paulrouget** [comment]
Fixed in master.
