### ISSUE TITLE
How to install Video DownloadHelper Companion App 1.6.3 on Endless OS

### ISSUE THREAD

**Issue by 92def** [aclap-dev/vdhcoapp#128]
Hello

I keep failing to install Video DownloadHelper Companion App on Endless OS.

Can you detail which steps I should follow please? https://www.downloadhelper.net/install-coapp?browser=firefox#other-installers

If Video DownloadHelper could be found in the Enless OS App Center, it would be marvellous!

Thanks

**Comment by mi-g** [comment]
I don't know specifics about Endless OS but since it is not Ubuntu nor Debian, you probably cannot use the `.deb` versions of the distribution. Pick the `.tar.gz` version corresponding to  your system architecture, 32 or 64 bits, untar to a system location, like `/usr/local` then execute once the binary with command line options `install --system` to complete the installation.

You should be able to do so using those commands:
```
sudo tar xf net.downloadhelper.coapp-1.6.3-1_amd64.tar.gz -C /usr/local
sudo /usr/local/net.downloadhelper.coapp-1.6.3/bin/net.downloadhelper.coapp-linux-64 install --system
```

**Comment by jntesteves** [comment]
I believe Endless OS uses Flatpak by default, in which case this is related to #114 and #137, and possibly the same solution applies.

**Comment by paulrouget** [comment]
Closing in favor of https://github.com/aclap-dev/vdhcoapp/issues/159
