### ISSUE TITLE
Companion app cannot be found when using Flatpak builds of Firefox

### ISSUE THREAD

**Issue by nunyafukkinbizness** [aclap-dev/vdhcoapp#137]
The video downloadhelper Companion app cannot be found when using Flatpak or Snap builds of Firefox
Why was this issue closed when it hasn't been solved? This issue has existed for at least a year! Work on it! I have found another add on that works without any companion app for most sites and yet another one that works in youtube without a companion app! I love video downloadhelper and used it for many years but if it isn't fixed to work with Ubuntu 22.04 104.0.1 (64-bit) Snap and Flatpak versions it is useless for Ubuntu, and I'm sure other Linux users. Linux is growing don't lose your audience by ignoring them!

**Comment by RylanSchaeffer** [comment]
@nunyafukkinbizness do you have a solution? I have this same issue!

**Comment by posita** [comment]
Ref #91. Also, from https://bugzilla.mozilla.org/show_bug.cgi?id=1621763#c5 regarding possible solutions:

> The portal discovery idea and the socket communication suggestions seem promising for providing a more secure way of supporting native messaging from the Firefox flatpak. Another method I was wondering about was using Flatpak Extensions. I am not that familiar with how they work exactly but I think they act as a kind of overlay onto the flatpak the way that the app flatpak overlays the runtime flatpak. My thought was that perhaps the native messaging host application could be packaged into an extension and optionally installed on top of the Firefox flatpak. I think this might work well for something like the KDE Plasma/Browser integration because the native messaging app is just a small program that needs a dbus permission to talk to for its functionality. Perhaps other native messaging hosts do not fit this model.
> 
> One other thing I thought was interesting was that the Zotero WebExtension worked fine with both Zotero and Firefox as flatpaks. The reason for this is that the Zotero application runs an http server and the Zotero WebExtension communicates with that server via http. Since both flatpaks have the network permission, the WebExtension was able to communicate with the application just as it normally does.

**Comment by SifiW** [comment]
You can uninstall Firefox and install from PPA following these instructions and the companion app will be found again. https://github.com/mi-g/vdhcoapp/issues/133#issuecomment-1165334764

**Comment by knghtbrd** [comment]
StreamDeck doesn't use PPAs, but does use Flatpack Firefox. The solution is likely to use the program Flatseal to configure Firefox's sandbox to open access fore VDH to "see" coapp. If I understood what exactly what isn't happening, I could probably work out what needs to be done to fix it.

**Comment by justunsix** [comment]
Here is a workaround to get the Video Downloadhelper Companion App visible in the Flatpak Firefox so the add on can use it to download files. Workaround is based on ideas listed in the sources section. It involves:

- Copying the native messaging hosts configuration to the Flatpak Firefox configuration directory
- Granting access to the Companion app's binaries so the add on can see it.

## Workaround Steps

- Install the [Companion application](https://www.downloadhelper.net/install-coapp) using Linux - 64 bits - targz option and follow extra install instructions on the site. Extract it to a folder you choose. Copy the folder location, you will need it later.
- Copy the `net.downloadhelper.coapp.json` in a non-Flatpak Firefox's configuration folder generated during the Companion application install to the Flatpak Firefox's configuration folder. 
  - For example: `cp ~/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json ~/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts/` 
	- `~/.var/app/org.mozilla.firefox/.mozilla` is the Flatpak Firefox's folder. Create the `native-messaging-hosts` folder if it doesn't exist already in that folder.
	- `~/.mozilla/` is a non-Flatpak Firefox installation folder and will vary depending on your installation. In my case, I have the Ubuntu Snap version of Firefox installed before installing the Flatpak version.
- Give the Flatpak Firefox read only access to the Companion application and its binaries.
  - For example, using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal), add the location from the first step into Firefox's permissions under > Filesystem > Other Files > Add Folder `<your-folder-name-from-first-step-net.downloadhelper.coapp>/:ro`
	- `ro` means read only
- Restart the Flatpak Firefox
- Check the Companion App is recognized in Firefox. Try downloading a video.

The workaround is granting extra permissions to the Flatpak Firefox so use with care.

## Sources 

Thank you to these posts for contributing to the steps above.

1. https://github.com/mi-g/vdhcoapp/issues/91#issuecomment-1247940392 - insecure work around 
2. https://github.com/mi-g/vdhcoapp/issues/137#issuecomment-1274491105 - idea to give Firefox permissions to see the Companion application
3. [How to install Video DownloadHelper coapp in flatpak Chrome...](https://forums.linuxmint.com/viewtopic.php?f=42&t=383814)

## Problems

Problems I encountered and fixes.

The companion app keeps saying "Verifying..."

- It turned out I put the `net.downloadhelper.coapp.json` in the wrong folder. Check the file is in the correct Flatpak Firefox configuration folder.

Downloads failing with read only filesystem error. 

- I had to grant read and write access to the download folder to Firefox. There may be a more secure way of doing this.
  - For example, using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal), add the download location to Firefox's permissions under > Filesystem > Other Files > Add Folder `~/Downloads:rw`
	- `rw` means read and write

**Comment by CHJ85** [comment]
This is still an issue.
Will there be a flatpak available soon?
I'd really like to use this addon.

**Comment by jntesteves** [comment]
Installing for Firefox Flatpak is super easy, it just needs a small adaptation to the [installation instructions](https://www.downloadhelper.net/install-coapp#extra-targz64):

```
tar xf net.downloadhelper.coapp-1.6.3-1_amd64.tar.gz -C ~/.var/app/org.mozilla.firefox
flatpak run --command=$HOME/.var/app/org.mozilla.firefox/net.downloadhelper.coapp-1.6.3/bin/net.downloadhelper.coapp-linux-64 org.mozilla.firefox install --user
```

I'd also recommend changing the default download folder in the extension's settings to `~/Downloads`. No messing with permissions necessary.

**Comment by CHJ85** [comment]
Thank you so much @jntesteves

**Comment by cheako** [comment]
Here is another solution: https://github.com/mi-g/vdhcoapp/issues/91#issuecomment-1247940392

**Comment by paulrouget** [comment]
Is this still a problem with the latest version of Firefox? It's supposed to have been fixed.

**Comment by paulrouget** [comment]
Closing in favor of https://github.com/aclap-dev/vdhcoapp/issues/159

**Comment by CHJ85** [comment]
I'm no longer using the Flatpak version anymore due to all kinds of problems.
However. vdhcoapp is not recognized by latest Firefox build 117.0, on Manjaro Linux.
This is not related to the Flatpak issue though.

**Comment by paulrouget** [comment]
> I'm no longer using the Flatpak version anymore due to all kinds of problems. However. vdhcoapp is not recognized by latest Firefox build 117.0, on Manjaro Linux. This is not related to the Flatpak issue though.

Can you file a specific issue for that? I can assist in debugging.

**Comment by CHJ85** [comment]
@paulrouget Sure, and thank you.
