### ISSUE TITLE
ungoogled-chrome doesn't see companion app

### ISSUE THREAD

**Issue by ewoks** [aclap-dev/vdhcoapp#193]
[Ungoogled-Chromium Browser](https://github.com/ungoogled-software/ungoogled-chromium) Version 120.0.6099.129 on Fedora 39.

As with other browsers ungoogled-chromium keeps the configs in  `~/.config` and as expected installer doesn't know about this browser. However manual copy of the `net.downloadhelper.coapp.json` to the `/home/<user>/.config/ungoogled-chromium/NativeMessagingHosts/` from respectve folder of `google-chrome` or `chromium` doesn't help extension to find coapp.
Default recommended debugging steps yell no results.

Any hints or advices would be welcome

**Comment by paulrouget** [comment]
How do you install and run ungoogled chrome?

Is it a snap, a flatpak or do you use apparmor?

**Comment by paulrouget** [comment]
If I'm not mistaken, this configuration (snap + chrome + native messenging) is just no supported. With ungoogled or regular chrome.

**Comment by ewoks** [comment]
is that different that google chrome?  or you think it's about snap format?
cause I just tried with it with Version 120.0.6099.199 (Official Build) (64-bit) which is basically the same google flavoured version and it works...
What I noticed is that ` ~/vdhcoapp-2.0.10/vdhcoapp install` didn't take into account existing `ungoogled-chromium`

**Comment by ewoks** [comment]
Oh wait, it seems that I just found it... :)
I manually copied configuration stored in `net.downloadhelper.coapp.json`  of another browser to the `~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium/NativeMessagingHosts/` and in the extension settings companion app shows as installed, so it works!!! 🥳🥳🥳

**Comment by ewoks** [comment]
hopefully someone else find it useful when configuring `ungoogled-chromium` or similar flavours

**Comment by paulrouget** [comment]
com.github.Eloston.UngoogledChromium should already be supported. I'm surprised it doesn't work out of the box.

**Comment by paulrouget** [comment]
I'll look into this.

**Comment by norweeg** [comment]
It's likely that, despite linking itself in the sandbox for ungoogled-chromium, it doesn't create the native messaging hosts file similar to how it fails to create this file flatpak-installed Microsoft Edge (see #207)

**Comment by paulrouget** [comment]
Ok, so for some flavors of google browsers, we only do half the work. Edge and Ungoogled are missing some files. I'll spawn a new release with a fix in the coming days once @norweeg confirms [this works](https://github.com/aclap-dev/vdhcoapp/issues/207#issuecomment-1907299893). 

Sadly I can't try that myself as Edge doesn't support my computer architecture.

**Comment by paulrouget** [comment]
This will be fixed in CoApp 2.0.14

**Comment by UpstairsH** [comment]
Hello! Posting to this closed/completed topic because this also concerns Chrome.

I am having difficulty getting the app to recognize the coapp. First time installing on a non-windows machine and I'm not super conversant with the technology, but I can read and am patient!

Chromebook running Google Chrome 137.0.7151.123 (Official Build) (64-bit)

I installed the Linux Development Environment. It identifies itself as penguin/Crostini

From within the Terminal, I ran 
curl -sSLf https://github.com/aclap-dev/vdhcoapp/releases/latest/download/install.sh | bash

which tells me the following

VdhCoApp : VdhCoApp is ready to be used
CoApp successfuly installed under '~/.local/share/vdhcoapp'.

After a machine/browser restart, when trying to download a video, I get the same notice that "This operation requires an external application to be completed." Clicking through to 'More Settings' shows "Companion App not installed"

When I run the diagnostic command ~/.local/share/vdhcoapp/vdhcoapp --info

I receive the following

{
  "id": "net.downloadhelper.coapp",
  "name": "VdhCoApp",
  "version": "2.0.19",
  "binary": "/home/USERNAME/.local/share/vdhcoapp/vdhcoapp",
  "displayName": "VdhCoApp",
  "description": "Video DownloadHelper companion app",
  "target": {
    "os": "linux",
    "arch": "aarch64",
    "node": "18"
  },
  "home": "/home/USERNAME",
  "converterBinary": "/home/USERNAME/.local/share/vdhcoapp/ffmpeg",
  "converterBase": "ffmpeg",
  "converterBaseVersion": "n6.1-9-g63b936e978"
}

Please help if you are able and willing. :D
